[package]
name = "rustlang"
version = "0.1.0"
authors = ["Pavel Bunin <p.bunin@roseltorg.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
